### ISSUE TITLE
Use Serverless to Create SQS and Lambdas

### ISSUE THREAD

**Issue by jawad46** [data-engineering-bir-1/team-3-project#23]
90% currently complete...

**Extract Lambda**:
- [x] Event: Cloud-watch trigger (time of day)
- [x] Permissions: Write Messages to SQS 
- [x] Permissions: Read from S3 Bucket

**Load Lambda**:
- [x] Permissions: Write to Redshift

**Comment by CSemper** [comment]
- [ ] Do the Lambdas have the correct permissions?
- [ ] Do the Lambdas have the correct triggers set up?
- [ ] Is the 1st SQS (from Extract Lambda to Transform Lambda) correctly set up?
- [ ] Is the 2nd SQS (from Transform Lambda to Load Lambda) correctly set up?
